# Generated by Django 4.1.10 on 2025-05-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourproject',
            name='about',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
